-- ============================================================
-- HUM Network Digital Sales Dashboard — Full Seed Data
-- Run in Supabase SQL Editor (Project → SQL Editor → New Query)
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. CLIENTS — DIRECT BRANDS
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.clients (name, type, industry, region, status, contact_name, contact_email, contact_phone, entertainment_budget, notes) VALUES
  ('Nestlé Pakistan',           'brand', ARRAY['FMCG'],                   'Lahore',     'active', 'Zulfiqar Ali',       'z.ali@nestle.pk',            '+92-42-5870-1000', 18000000, 'Title sponsor of HUM Spelling Whizz. Via Pak Media Com. Priority account.'),
  ('Jazz (Mobilink)',           'brand', ARRAY['Telecom'],                 'Islamabad',  'active', 'Omer Sheikh',        'o.sheikh@jazz.com.pk',       '+92-51-111-925922',16500000, 'Long-term partner — Presenting sponsor across multiple dramas. Billed as Mobilink in legacy reports.'),
  ('HBL',                       'brand', ARRAY['Banking & Finance'],       'Karachi',    'active', 'Aisha Baig',         'a.baig@hbl.com',             '+92-21-111-000425', 5000000, 'Clock widget, drama sponsorships, whitelisting. Via BrainChild/Starcom.'),
  ('UBL',                       'brand', ARRAY['Banking & Finance'],       'Karachi',    'active', 'Kamran Mirza',       'k.mirza@ubl.com.pk',         '+92-21-111-825888', 2400000, 'Glam Magazine and HUM News recurring placements.'),
  ('Haier Pakistan',            'brand', ARRAY['Technology'],              'Karachi',    'active', 'Wang Li',            'wang.li@haier.com.pk',       '+92-21-3570-0041',  2000000, 'Active HUM News and HUM TV social advertiser. Via IO Digital / Mesh Media.'),
  ('K&N''s Foods',              'brand', ARRAY['Food & Beverage'],         'Karachi',    'active', 'Tariq Hassan',       't.hassan@kns.com.pk',        '+92-21-3586-5490',  1500000, 'Product launch campaigns on HUM Network website. Via Adcom.'),
  ('OGDCL',                     'brand', ARRAY['Energy & Utilities'],      'Islamabad',  'active', 'Dr. Nadeem Babar',   'n.babar@ogdcl.com',          '+92-51-9101-0001',  4000000, 'Direct govt brand — major Spelling Whizz 2025 sponsor (PKR 4M direct).'),
  ('Bank Alfalah',              'brand', ARRAY['Banking & Finance'],       'Karachi',    'active', 'Saima Khan',         's.khan@bankalfalah.com',     '+92-21-3811-0000',   500000, 'Occasional social media buys on HUM TV Instagram.'),
  ('Dawlance',                  'brand', ARRAY['Technology'],              'Karachi',    'active', 'Faisal Niaz',        'f.niaz@dawlance.com.pk',     '+92-21-3568-5870',  3500000, 'Whitelisting and drama placement via BrainChild/Starcom.'),
  ('SNGPL',                     'brand', ARRAY['Energy & Utilities'],      'Lahore',     'active', 'Arif Hameed',        'a.hameed@sngpl.com.pk',      '+92-42-9920-1000',  2000000, 'Recurring HUM News website + Instagram via Hakuna Matata.'),
  ('EBM (English Biscuit Makers)', 'brand', ARRAY['FMCG'],               'Karachi',    'active', 'Zehra Hussain',      'z.hussain@ebm.com.pk',       '+92-21-3240-9030',   800000, 'Coronet Foods brand via Starcom — HUM News website placement.'),
  ('Dubai Economy & Tourism',   'brand', ARRAY['Travel & Tourism'],        'Karachi',    'active', 'Ahmed Al Rashdi',    'a.rashdi@det.ae',            '+971-4-201-7500',   5000000, 'International direct brand — web-series and exclusive content partnership.'),
  ('BYD Pakistan',              'brand', ARRAY['Automotive'],              'Karachi',    'active', 'Chen Wei',           'chen.wei@byd.pk',            '+92-21-3529-9990',   800000, 'EV entrant exploring drama integration and social media presence.'),
  ('Avari Hotels',              'brand', ARRAY['Travel & Tourism'],        'Lahore',     'active', 'Nilofer Saigol',     'n.saigol@avari.com',         '+92-42-3636-5566',  3500000, 'Barter deal partner — Spelling Whizz 2025 hotel sponsor.'),
  ('FBR',                       'brand', ARRAY['Government'],              'Islamabad',  'active', 'Raja Jahangir',      'r.jahangir@fbr.gov.pk',      '+92-51-9205-3330',   600000, 'Tax awareness campaigns via Resonance Digital and DGS.')
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- 2. CLIENTS — AGENCIES
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.clients (name, type, industry, region, status, contact_name, contact_email, contact_phone, entertainment_budget, notes) VALUES
  ('IG Square',                 'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Imran Ghazi',        'imran@igsquare.pk',          '+92-21-3550-7070', 40000000, 'Highest billing agency FY24-25 — PKR 38.4M in H1. BCW + HUM Awards packages.'),
  ('Pak Media Com',             'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Saad Malik',         'saad@pakmediacom.pk',        '+92-21-3400-8080', 18000000, 'Handled Nestlé Spelling Whizz (PKR 17.75M). Growing rapidly.'),
  ('BrainChild / Starcom',      'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Sana Tariq',         'sana@brainchildpk.com',      '+92-21-3568-5500', 12000000, 'Present in all 3 FYs — HBL, Dawlance, Syngenta. Reliable mid-large agency.'),
  ('GroupM',                    'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Zara Hussain',       'zara@groupm.com',            '+92-21-3521-3030',  8000000, 'Down 85% H1-over-H1 — recovery priority. Major multinational clients under them.'),
  ('Time & Space',              'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Nasir Ahmed',        'nasir@timeandspace.pk',      '+92-21-3580-4040',  3000000, 'Down 79% H1-over-H1 — FFC and other clients need reactivation.'),
  ('Media Networks',            'agency', ARRAY['Media & Entertainment'],  'Lahore',     'active', 'Shahid Iqbal',       'shahid@medianetworks.pk',    '+92-42-3590-6060',  8000000, 'Consistent recurring billings across FYs. Lahore-based, strong regional clients.'),
  ('Starcrest',                 'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Amna Rehman',        'amna@starcrest.pk',          '+92-21-3500-5050',  7500000, 'Growing year-on-year. Strong for drama and event packages.'),
  ('Digital Creation',          'agency', ARRAY['Technology'],             'Lahore',     'active', 'Bilal Hassan',       'bilal@digitalcreation.pk',   '+92-42-3511-9090',  8500000, 'Up 154% H1-over-H1. Digital-first agency with strong social media capabilities.'),
  ('Wings Media',               'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Ahsan Rao',          'ahsan@wingsmedia.pk',        '+92-21-3519-1010',  7500000, 'New entrant FY24-25. Choco Spelling Whizz and Innovative brand campaigns.'),
  ('Adcom',                     'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Lubna Pasha',        'lubna@adcom.com.pk',         '+92-21-3480-2020',  3500000, 'K&N product launch campaigns. Mid-tier consistent agency.'),
  ('Mesh Media',                'agency', ARRAY['Media & Entertainment'],  'Karachi',    'active', 'Raza Shah',          'raza@meshmedia.pk',          '+92-21-3507-3030',  2000000, 'HUM Awards Haier posts. Emerging digital-first agency.'),
  ('Resonance Digital',         'agency', ARRAY['Technology'],             'Lahore',     'active', 'Fariha Qureshi',     'fariha@resonancedigital.pk', '+92-42-3555-4040',  1500000, 'Govt digital campaigns — FBR, Ministry of Planning, Punjab Govt.'),
  ('Hakuna Matata',             'agency', ARRAY['Technology'],             'Islamabad',  'active', 'Usama Khan',         'usama@hakunamatata.pk',      '+92-51-2878-5050',  2500000, 'SNGPL and PSER recurring advertiser. Islamabad-based digital agency.'),
  ('IO Digital',                'agency', ARRAY['Technology'],             'Karachi',    'active', 'Imad Baig',          'imad@iodigital.pk',          '+92-21-3440-6060',  1500000, 'Haier campaigns on HUM News website and digital placements.'),
  ('Digital Marvels',           'agency', ARRAY['Technology'],             'Lahore',     'active', 'Raheela Saeed',      'raheela@digitalmarvels.pk',  '+92-42-3512-7070',  2000000, 'SMOG and DGPR awareness campaigns. Growing govt-focused digital agency.')
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- 3. SHOWS
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.shows (name, channel, schedule, status, youtube_upload, episode_count, paid_drama_budget, presenting_client_id, powered_client_id)
VALUES
  ('Hum Kalam', 'HUM TV', 'Mon–Thu 8:00 PM PKT', 'Live', true, 85, 12000000,
    (SELECT id FROM public.clients WHERE name = 'Jazz (Mobilink)' LIMIT 1), NULL),
  ('Good Morning Pakistan', 'HUM TV', 'Mon–Sat 9:00 AM PKT', 'Live', true, 220, NULL,
    (SELECT id FROM public.clients WHERE name = 'Nestlé Pakistan' LIMIT 1),
    (SELECT id FROM public.clients WHERE name = 'HBL' LIMIT 1)),
  ('Raqs-e-Bismil', 'HUM TV', 'Sat–Sun 8:00 PM PKT', 'Completed', true, 56, 8500000,
    (SELECT id FROM public.clients WHERE name = 'IG Square' LIMIT 1), NULL),
  ('Dil Awaiz', 'HUM TV', 'Mon–Fri 9:00 PM PKT', 'Upcoming', false, NULL, 10000000, NULL, NULL),
  ('Masala Mornings', 'Masala TV', 'Mon–Fri 9:00 AM PKT', 'Live', true, 145, NULL,
    (SELECT id FROM public.clients WHERE name = 'K&N''s Foods' LIMIT 1), NULL),
  ('HUM News Prime Time', 'HUM News', 'Mon–Fri 9:00 PM PKT', 'Live', false, NULL, NULL, NULL, NULL)
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- 4. DEALS — assigned to each team member
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.deals (name, type, client_id, channel, tier, start_date, end_date, value_net, status, assigned_to, notes, agency_commission_pct) VALUES

-- Aamish Mirza
('Haier - HUM Awards Social Posts 2026',          'Social Media Posts',   (SELECT id FROM public.clients WHERE name = 'Haier Pakistan' LIMIT 1),            ARRAY['HUM TV'],             'Powered By',  '2026-06-01', '2026-06-30',  1200000, 'In Negotiation', 'Aamish Mirza', 'POC: Wang Li. Posts for HUM Awards on HUM TV Insta/Facebook. Negotiating quantity and rate.', 0),
('K&N''s - Website Banners Q3 2026',              'Website Banners',      (SELECT id FROM public.clients WHERE name = 'K&N''s Foods' LIMIT 1),               ARRAY['HUM Network'],        'Associated',  '2026-07-01', '2026-09-30',   450000, 'Locked',         'Aamish Mirza', 'POC: Tariq Hassan. Homepage + category banners. RO expected by June 20.', 0),
('BYD Pakistan - Drama Integration Spotlight',    'Drama Integration',    (SELECT id FROM public.clients WHERE name = 'BYD Pakistan' LIMIT 1),               ARRAY['HUM TV'],             'Presenting',  '2026-08-01', '2026-10-31',   800000, 'Prospecting',    'Aamish Mirza', 'POC: Chen Wei. First EV brand on HUM TV. Initial pitch done — awaiting budget approval.', 0),
('Bank Alfalah - Social Media Posts Package',     'Social Media Posts',   (SELECT id FROM public.clients WHERE name = 'Bank Alfalah' LIMIT 1),               ARRAY['HUM TV'],             '',            '2026-06-15', '2026-07-15',   650000, 'Pitch Sent',     'Aamish Mirza', 'POC: Saima Khan. Instagram + Facebook posts for Alfalah digital campaign. Proposal sent June 10.', 0),

-- Sarfaraz
('Nestlé - HUM Spelling Whizz 2026',              'Event Sponsorship',    (SELECT id FROM public.clients WHERE name = 'Nestlé Pakistan' LIMIT 1),            ARRAY['HUM Network'],        'Presenting',  '2026-09-01', '2026-10-31', 20000000, 'Under Process',  'Sarfaraz',     'POC: Zulfiqar Ali / Saad Malik (Pak Media Com). Title sponsorship for Spelling Whizz 2026. Nestlé HO approval pending.', 15),
('Pak Media Com - Drama Sponsorship Ramzan 2027', 'Drama Sponsorship',    (SELECT id FROM public.clients WHERE name = 'Pak Media Com' LIMIT 1),              ARRAY['HUM TV'],             'Presenting',  '2027-02-01', '2027-03-31',  3500000, 'Locked',         'Sarfaraz',     'POC: Saad Malik. Prime Ramzan drama slot. RO received June 5.', 15),
('OGDCL - Digital Awareness Campaign',            'Social Media Posts',   (SELECT id FROM public.clients WHERE name = 'OGDCL' LIMIT 1),                     ARRAY['HUM News'],           '',            '2026-07-01', '2026-08-31',  4000000, 'RO Received',    'Sarfaraz',     'POC: Dr. Nadeem Babar. Corporate awareness — social + website. Direct government brand. RO in hand.', 0),

-- Talal
('HBL - Brand Awareness Clock Widget',            'Website Banners',      (SELECT id FROM public.clients WHERE name = 'HBL' LIMIT 1),                       ARRAY['HUM News'],           '',            '2026-02-01', '2026-03-31',  3500000, 'Billed',         'Talal',        'POC: Aisha Baig. Clock widget on HUM News Urdu website. Invoiced March 2026. Via BrainChild/Starcom.', 15),
('BrainChild/Starcom - Drama Sponsorship Q3',     'Drama Sponsorship',    (SELECT id FROM public.clients WHERE name = 'BrainChild / Starcom' LIMIT 1),      ARRAY['HUM TV'],             'Presenting',  '2026-08-01', '2026-12-31',  8000000, 'In Negotiation', 'Talal',        'POC: Sana Tariq. Multi-brand Q3 package (Dawlance + HBL). Rates being negotiated.', 15),
('SNGPL - Digital Awareness Package',             'Website Banners',      (SELECT id FROM public.clients WHERE name = 'SNGPL' LIMIT 1),                     ARRAY['HUM News'],           '',            '2026-05-01', '2026-08-31',   880000, 'Locked',         'Talal',        'POC: Arif Hameed. Monthly HUM News website + Instagram banners via Hakuna Matata. 4-month block.', 15),

-- Asif (Senior Manager — larger deals)
('Jazz - Annual Digital Partnership FY26-27',     'Drama Sponsorship',    (SELECT id FROM public.clients WHERE name = 'Jazz (Mobilink)' LIMIT 1),           ARRAY['HUM TV', 'HUM Network'], 'Presenting', '2026-07-01', '2027-06-30', 16500000, 'Locked',        'Asif',         'POC: Omer Sheikh. Annual Presenting deal across dramas + digital. Historically PKR 15-16M/year. Strategic account.', 0),
('IG Square - Events Package 2026',               'Event Sponsorship',    (SELECT id FROM public.clients WHERE name = 'IG Square' LIMIT 1),                 ARRAY['HUM TV', 'HUM Network'], 'Presenting', '2026-09-01', '2026-12-31', 12000000, 'RO Received',   'Asif',         'POC: Imran Ghazi. BCW + HUM Awards package. Highest-value IG Square booking. RO received June 1.', 15),
('Mesh Media - HUM Awards Haier Integration',     'Event Sponsorship',    (SELECT id FROM public.clients WHERE name = 'Mesh Media' LIMIT 1),                ARRAY['HUM TV'],             'Powered By',  '2026-06-01', '2026-06-30',  1500000, 'Billed',         'Asif',         'POC: Raza Shah. Haier brand integration in HUM Awards. Invoiced. Via Mesh Media.', 15),
('GroupM - Drama Integration H2 FY26-27',         'Drama Integration',    (SELECT id FROM public.clients WHERE name = 'GroupM' LIMIT 1),                    ARRAY['HUM TV'],             'Associated',  '2026-10-01', '2026-12-31',  5000000, 'Prospecting',    'Asif',         'POC: Zara Hussain. GroupM reactivation — down 85% vs last year. Meeting scheduled for Q1 FY26-27 planning.', 15),

-- Erum
('UBL - Brand Campaign FY26-27',                  'Social Media Posts',   (SELECT id FROM public.clients WHERE name = 'UBL' LIMIT 1),                       ARRAY['HUM TV', 'HUM News'], '',            '2026-07-01', '2026-09-30',   600000, 'Pitch Sent',     'Erum',         'POC: Kamran Mirza. HUM News website + Glam Magazine digital placement. Pitch presented June 8.', 0),
('Wings Media - Social Bundle Ramzan 2027',        'Social Media Posts',   (SELECT id FROM public.clients WHERE name = 'Wings Media' LIMIT 1),               ARRAY['HUM TV', 'HUM News'], '',            '2027-03-01', '2027-04-30',  2800000, 'Under Process',  'Erum',         'POC: Ahsan Rao. Ramzan social bundle via Wings — multiple brand clients. Activation planning in progress.', 15),
('Dawlance - Product Launch Integration',          'Product Integration',  (SELECT id FROM public.clients WHERE name = 'Dawlance' LIMIT 1),                  ARRAY['HUM TV'],             'Powered By',  '2026-08-01', '2026-10-31',  1800000, 'Locked',         'Erum',         'POC: Faisal Niaz. New product launch integration in Masala TV morning show + HUM TV drama. Via Starcom.', 15),

-- Ans
('Adcom - K&N Product Launches 2026',             'Product Integration',  (SELECT id FROM public.clients WHERE name = 'Adcom' LIMIT 1),                     ARRAY['HUM Network'],        '',            '2026-01-01', '2026-03-31',   450000, 'Completed',      'Ans',          'POC: Lubna Pasha. K&N Croissant and main product launch on HUM Network. Completed successfully.', 15),
('Media Networks - Monthly Digital Package',      'Website Banners',      (SELECT id FROM public.clients WHERE name = 'Media Networks' LIMIT 1),             ARRAY['HUM TV', 'HUM News'], '',            '2026-04-01', '2026-06-30',  1500000, 'RO Received',    'Ans',          'POC: Shahid Iqbal. Recurring monthly banners + social posts. Q4 renewal confirmed.', 15),
('EBM - Drama Sponsorship Season 2',              'Drama Sponsorship',    (SELECT id FROM public.clients WHERE name = 'EBM (English Biscuit Makers)' LIMIT 1), ARRAY['HUM TV'],          'Associated',  '2026-09-01', '2026-12-31',  2200000, 'In Negotiation', 'Ans',          'POC: Zehra Hussain. Season 2 EBM drama sponsorship via Starcom. H2 FY26-27 rates being discussed.', 15),

-- Meesum
('Starcrest - Social Media Q3 Bundle',            'Social Media Posts',   (SELECT id FROM public.clients WHERE name = 'Starcrest' LIMIT 1),                 ARRAY['HUM TV', 'HUM News'], '',            '2026-07-01', '2026-09-30',  1800000, 'Locked',         'Meesum',       'POC: Amna Rehman. Quarterly social posting package via Starcrest for multiple clients. RO expected June 25.', 15),
('Digital Creation - Banners & Posts Bundle',     'Website Banners',      (SELECT id FROM public.clients WHERE name = 'Digital Creation' LIMIT 1),           ARRAY['HUM News'],           '',            '2026-06-01', '2026-07-31',   600000, 'Pitch Sent',     'Meesum',       'POC: Bilal Hassan. HUM News digital banners + Instagram posts bundle. Lahore client — pitch done.', 15),
('Digital Marvels - SMOG Awareness Campaign',     'Social Media Posts',   (SELECT id FROM public.clients WHERE name = 'Digital Marvels' LIMIT 1),            ARRAY['HUM News'],           '',            '2025-12-01', '2026-01-31',   350000, 'Completed',      'Meesum',       'POC: Raheela Saeed. DGPR SMOG awareness winter 2025. Delivered on time.', 15);

-- ─────────────────────────────────────────────────────────────
-- 5. FOLLOW-UPS — 10 per team member (~70 total)
-- ─────────────────────────────────────────────────────────────

-- ── Aamish Mirza ──
INSERT INTO public.follow_ups (client_id, deal_id, follow_up_date, type, notes, status, next_action, next_follow_up_date) VALUES
((SELECT id FROM public.clients WHERE name='Haier Pakistan' LIMIT 1), (SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%Haier%' LIMIT 1), '2026-06-18', 'Call',              'POC: Wang Li. Confirm final social post counts + publish schedule for HUM Awards. Creative approval pending.', 'Pending',  'Share revised post count options and mock schedule', '2026-06-20'),
((SELECT id FROM public.clients WHERE name='Haier Pakistan' LIMIT 1), NULL, '2026-06-10', 'WhatsApp',         'POC: Wang Li. Sent rate card for HUM Awards digital package. He acknowledged receipt.', 'Done',     'Follow up on approval', '2026-06-18'),
((SELECT id FROM public.clients WHERE name='K&N''s Foods'   LIMIT 1), (SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%K&N%' LIMIT 1),   '2026-06-20', 'Email',             'POC: Tariq Hassan. Share banner size specs + placement mockups for Q3 website banners.', 'Pending',  'Send mockup with homepage placement', '2026-06-22'),
((SELECT id FROM public.clients WHERE name='K&N''s Foods'   LIMIT 1), NULL, '2026-06-05', 'In-Person Meeting','POC: Tariq Hassan. Visited K&N HQ Clifton. Discussed Q3 digital calendar. Positive on website banners.', 'Done', 'Send formal proposal', '2026-06-12'),
((SELECT id FROM public.clients WHERE name='BYD Pakistan'   LIMIT 1), (SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%BYD%' LIMIT 1),   '2026-06-25', 'Presentation',      'POC: Chen Wei. Present HUM TV auto-sector integration case studies. BYD wants to see past examples.', 'Pending','Prepare Dawlance/auto case study deck', '2026-06-28'),
((SELECT id FROM public.clients WHERE name='BYD Pakistan'   LIMIT 1), NULL, '2026-05-28', 'Call',              'POC: Chen Wei. First contact — exploring EV launch TV presence. Interested in drama + social combo.', 'Done',  'Prepare initial proposal', '2026-06-10'),
((SELECT id FROM public.clients WHERE name='Bank Alfalah'   LIMIT 1), (SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%Alfalah%' LIMIT 1),'2026-06-17', 'Email',             'POC: Saima Khan. Follow up on proposal sent June 10. Check if they need revised rates.', 'Pending',  'Offer volume discount if budget is tighter', '2026-06-19'),
((SELECT id FROM public.clients WHERE name='Bank Alfalah'   LIMIT 1), NULL, '2026-06-01', 'WhatsApp',         'POC: Saima Khan. Sent teaser rates for Instagram + Facebook posts package. She asked for formal proposal.', 'Done', 'Send formal proposal with case studies', '2026-06-10'),
((SELECT id FROM public.clients WHERE name='Haier Pakistan' LIMIT 1), NULL, '2026-05-15', 'Call',              'POC: Wang Li. Discussed extending HUM News partnership. Mentioned Q3 budget released.', 'Done',     'Prepare Q3 proposal', '2026-05-20'),
((SELECT id FROM public.clients WHERE name='K&N''s Foods'   LIMIT 1), NULL, '2026-05-20', 'Call',              'POC: Tariq Hassan. Introductory call on Q3 digital placement. Interested in HUM Network website.', 'Done', 'Schedule in-person meeting', '2026-06-05');

-- ── Sarfaraz ──
INSERT INTO public.follow_ups (client_id, deal_id, follow_up_date, type, notes, status, next_action, next_follow_up_date) VALUES
((SELECT id FROM public.clients WHERE name='Nestlé Pakistan' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%Nestlé%' LIMIT 1), '2026-06-19','Call',              'POC: Zulfiqar Ali. Check status of Nestlé HO approval for Spelling Whizz 2026 title sponsorship.', 'Pending', 'Escalate to Pak Media Com if no reply by June 22', '2026-06-22'),
((SELECT id FROM public.clients WHERE name='Nestlé Pakistan' LIMIT 1),NULL,'2026-06-08','In-Person Meeting', 'POC: Zulfiqar Ali + Saad Malik (Pak Media Com). Reviewed Spelling Whizz 2026 activation plan. Budget increased to PKR 20M.', 'Done', 'Share revised proposal', '2026-06-15'),
((SELECT id FROM public.clients WHERE name='Pak Media Com'   LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%Ramzan%' LIMIT 1),  '2026-06-22','Email',             'POC: Saad Malik. Confirm drama title and airing slot for Ramzan 2027 package. Share drama reel once finalised.', 'Pending','Send drama reel + slot confirmation', '2026-06-25'),
((SELECT id FROM public.clients WHERE name='Pak Media Com'   LIMIT 1),NULL,'2026-06-03','Call',              'POC: Saad Malik. Pak Media Com gave RO for Ramzan deal. Discussed creative delivery timeline.', 'Done',    'Send RO acknowledgement and invoice', '2026-06-10'),
((SELECT id FROM public.clients WHERE name='OGDCL'           LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%OGDCL%' LIMIT 1),   '2026-06-16','Call',              'POC: Dr. Nadeem Babar. Finalise content calendar for HUM News social package. 8-week campaign.', 'Pending', 'Share content calendar template', '2026-06-18'),
((SELECT id FROM public.clients WHERE name='OGDCL'           LIMIT 1),NULL,'2026-05-25','Email',             'POC: Dr. Nadeem Babar. Sent digital campaign proposal. RO received June 2.', 'Done',               'Book campaign slots and brief digital team', '2026-06-05'),
((SELECT id FROM public.clients WHERE name='Nestlé Pakistan' LIMIT 1),NULL,'2026-05-10','Presentation',      'POC: Zulfiqar Ali. Presented Spelling Whizz 2025 results deck + 2026 pitch. Very positive response.', 'Done','Send follow-up email with numbers', '2026-05-15'),
((SELECT id FROM public.clients WHERE name='Pak Media Com'   LIMIT 1),NULL,'2026-05-20','Call',              'POC: Saad Malik. Explored Q1 FY26-27 pipeline — 3 brands in consideration for drama slots.', 'Done',   'Shortlist drama options and send deck', '2026-06-01'),
((SELECT id FROM public.clients WHERE name='OGDCL'           LIMIT 1),NULL,'2026-06-10','WhatsApp',          'POC: Dr. Nadeem Babar. Confirmed RO details and campaign start date July 1.', 'Done',                'Issue invoice once RO formalised', '2026-06-15'),
((SELECT id FROM public.clients WHERE name='Nestlé Pakistan' LIMIT 1),NULL,'2026-06-24','Email',             'POC: Zulfiqar Ali. Send updated co-branding guidelines for Spelling Whizz 2026 to Nestlé brand team.', 'Pending','Share brand guideline document', '2026-06-26');

-- ── Talal ──
INSERT INTO public.follow_ups (client_id, deal_id, follow_up_date, type, notes, status, next_action, next_follow_up_date) VALUES
((SELECT id FROM public.clients WHERE name='HBL'                 LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Talal' AND name LIKE '%Starcom%' LIMIT 1),'2026-06-21','Call',             'POC: Sana Tariq (BrainChild/Starcom). Discuss HBL and Dawlance budget split for Q3 drama package.', 'Pending','Share package breakdown by brand', '2026-06-24'),
((SELECT id FROM public.clients WHERE name='BrainChild / Starcom' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Talal' AND name LIKE '%Starcom%' LIMIT 1),'2026-06-15','In-Person Meeting','POC: Sana Tariq. Initial rate negotiation for Q3 drama package. She requested revised rates.', 'Done',   'Send revised rates with volume discount', '2026-06-21'),
((SELECT id FROM public.clients WHERE name='SNGPL'               LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Talal' AND name LIKE '%SNGPL%' LIMIT 1),  '2026-06-18','Email',            'POC: Arif Hameed (SNGPL) + Usama Khan (Hakuna Matata). Confirm campaign live links and reporting format.', 'Pending','Share live links and weekly report template', '2026-06-20'),
((SELECT id FROM public.clients WHERE name='SNGPL'               LIMIT 1),NULL,'2026-06-01','Call',            'POC: Usama Khan (Hakuna Matata). Campaign locked. Discussed delivery timeline for 4-month block.', 'Done',  'Raise invoice and book slots', '2026-06-10'),
((SELECT id FROM public.clients WHERE name='HBL'                 LIMIT 1),NULL,'2026-05-20','Presentation',    'POC: Aisha Baig. Presented post-campaign report for clock widget. Client very satisfied. Explored renewals.', 'Done','Propose renewal and Q3 drama add-on', '2026-06-01'),
((SELECT id FROM public.clients WHERE name='HBL'                 LIMIT 1),NULL,'2026-06-12','Email',           'POC: Sana Tariq. HBL confirmed Rs 3.5M budget for Q3 drama and digital combo.', 'Done',           'Prepare deal sheet and send to Talal for approval', '2026-06-15'),
((SELECT id FROM public.clients WHERE name='BrainChild / Starcom' LIMIT 1),NULL,'2026-05-28','Call',           'POC: Sana Tariq. Discussed Dawlance new product launch plans — interested in morning show integration.', 'Done','Include Masala TV Mornings option in Q3 proposal', '2026-06-10'),
((SELECT id FROM public.clients WHERE name='SNGPL'               LIMIT 1),NULL,'2026-05-15','WhatsApp',        'POC: Usama Khan. Shared HUM News website stats and readership report for SNGPL pitch.', 'Done',       'Follow up for feedback', '2026-05-25'),
((SELECT id FROM public.clients WHERE name='HBL'                 LIMIT 1),NULL,'2026-06-25','Call',            'POC: Aisha Baig. Check if HBL wants to renew clock widget for Q3. Budget discussion.', 'Pending',    'Confirm renewal budget and book slot', '2026-06-28'),
((SELECT id FROM public.clients WHERE name='BrainChild / Starcom' LIMIT 1),NULL,'2026-06-28','Email',          'POC: Sana Tariq. Send final drama package proposal for Q3 with slot options and rates.', 'Pending',   'Follow up 3 days after sending', '2026-07-01');

-- ── Asif ──
INSERT INTO public.follow_ups (client_id, deal_id, follow_up_date, type, notes, status, next_action, next_follow_up_date) VALUES
((SELECT id FROM public.clients WHERE name='Jazz (Mobilink)' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%Jazz%' LIMIT 1),    '2026-06-20','In-Person Meeting', 'POC: Omer Sheikh. Annual review meeting — discuss FY26-27 plans and drama slate. Jazz wants priority drama placement.', 'Pending','Share FY26-27 drama calendar', '2026-06-23'),
((SELECT id FROM public.clients WHERE name='Jazz (Mobilink)' LIMIT 1),NULL,'2026-06-05','Call',              'POC: Omer Sheikh. RO renewal confirmed for Annual Partnership. Slight budget increase to Rs 16.5M.', 'Done',   'Issue formal deal sheet and invoice', '2026-06-12'),
((SELECT id FROM public.clients WHERE name='IG Square'       LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%IG Square%' LIMIT 1),'2026-06-22','Email',             'POC: Imran Ghazi. Confirm BCW 2026 activation requirements — stage branding, social posts, press coverage.', 'Pending','Share BCW activation checklist', '2026-06-25'),
((SELECT id FROM public.clients WHERE name='IG Square'       LIMIT 1),NULL,'2026-06-01','In-Person Meeting', 'POC: Imran Ghazi. RO received for Events Package. Reviewed activation plan for BCW + HUM Awards.', 'Done', 'Issue invoice and brief events team', '2026-06-08'),
((SELECT id FROM public.clients WHERE name='GroupM'          LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%GroupM%' LIMIT 1),   '2026-07-05','Presentation',      'POC: Zara Hussain. Present FY26-27 drama slate and new digital packages. Key GroupM reactivation meeting.', 'Pending','Prepare comprehensive GroupM pitch deck', '2026-07-08'),
((SELECT id FROM public.clients WHERE name='GroupM'          LIMIT 1),NULL,'2026-05-22','Call',              'POC: Zara Hussain. Cold call after 6-month gap. She is open to meeting for FY26-27 planning.', 'Done',    'Schedule July meeting for FY26-27 pitch', '2026-07-05'),
((SELECT id FROM public.clients WHERE name='Mesh Media'      LIMIT 1),NULL,'2026-06-14','Call',              'POC: Raza Shah. HUM Awards invoice raised. Confirmed client satisfaction with Haier campaign delivery.', 'Done','Explore Q3 Haier renewal via Mesh Media', '2026-07-01'),
((SELECT id FROM public.clients WHERE name='Jazz (Mobilink)' LIMIT 1),NULL,'2026-05-10','WhatsApp',          'POC: Omer Sheikh. Shared FY25-26 full campaign performance report with Jazz brand team.', 'Done',         'Schedule annual review', '2026-06-05'),
((SELECT id FROM public.clients WHERE name='IG Square'       LIMIT 1),NULL,'2026-05-28','Call',              'POC: Imran Ghazi. Discussed BCW 2026 budget — IG Square increasing event spend to Rs 12M this year.', 'Done','Prepare events proposal', '2026-06-01'),
((SELECT id FROM public.clients WHERE name='GroupM'          LIMIT 1),NULL,'2026-06-15','Email',             'POC: Zara Hussain. Sent GroupM reactivation pitch email. Offered exclusive drama package with price hold.', 'Done','Follow up if no reply by June 22', '2026-06-22'),
((SELECT id FROM public.clients WHERE name='Jazz (Mobilink)' LIMIT 1),NULL,'2026-06-25','Call',              'POC: Omer Sheikh. Pre-FY kickoff call — confirm drama placements for July-September quarter.', 'Pending',  'Share Q1 FY26-27 drama placement schedule', '2026-06-28');

-- ── Erum ──
INSERT INTO public.follow_ups (client_id, deal_id, follow_up_date, type, notes, status, next_action, next_follow_up_date) VALUES
((SELECT id FROM public.clients WHERE name='UBL'         LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Erum' AND name LIKE '%UBL%' LIMIT 1),      '2026-06-19','Email',            'POC: Kamran Mirza. Follow up on proposal for HUM News + Glam digital package. Sent June 8.', 'Pending', 'Call if no email reply by June 21', '2026-06-21'),
((SELECT id FROM public.clients WHERE name='UBL'         LIMIT 1),NULL,'2026-06-08','Presentation',    'POC: Kamran Mirza. Presented HUM News website stats + Glam audience demographics. Good reception.', 'Done','Send follow-up email with pricing', '2026-06-12'),
((SELECT id FROM public.clients WHERE name='Wings Media' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Erum' AND name LIKE '%Wings%' LIMIT 1),    '2026-06-23','Call',            'POC: Ahsan Rao. Confirm client brand list under Wings for Ramzan social bundle. Need to brief social team.', 'Pending','Brief social team once brands confirmed', '2026-06-26'),
((SELECT id FROM public.clients WHERE name='Wings Media' LIMIT 1),NULL,'2026-06-10','In-Person Meeting','POC: Ahsan Rao. Wings Media HQ visit. Reviewed Ramzan 2027 plan — Rs 2.8M deal confirmed pending activation plan.', 'Done','Send activation plan for approval', '2026-06-18'),
((SELECT id FROM public.clients WHERE name='Dawlance'    LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Erum' AND name LIKE '%Dawlance%' LIMIT 1), '2026-06-25','Call',            'POC: Faisal Niaz. Finalise product launch drama integration brief. Filming starts August 1.', 'Pending',  'Share integration brief template', '2026-06-28'),
((SELECT id FROM public.clients WHERE name='Dawlance'    LIMIT 1),NULL,'2026-06-12','Email',           'POC: Sana Tariq (BrainChild/Starcom re: Dawlance). Deal locked. Confirmed drama slot for August.', 'Done',  'Issue invoice and brief content team', '2026-06-18'),
((SELECT id FROM public.clients WHERE name='UBL'         LIMIT 1),NULL,'2026-05-25','Call',            'POC: Kamran Mirza. Initial outreach — UBL digital campaign planning. Interested in Glam Magazine.', 'Done',  'Prepare Glam + HUM News combo proposal', '2026-06-08'),
((SELECT id FROM public.clients WHERE name='Wings Media' LIMIT 1),NULL,'2026-05-30','WhatsApp',        'POC: Ahsan Rao. Shared Ramzan 2026 campaign results from other agencies — proof of concept.', 'Done',     'Schedule in-person meeting', '2026-06-10'),
((SELECT id FROM public.clients WHERE name='Dawlance'    LIMIT 1),NULL,'2026-05-20','Presentation',    'POC: Faisal Niaz (via Sana Tariq). Presented morning show integration case study for Dawlance launch.', 'Done','Confirm interest and get budget approval', '2026-06-05'),
((SELECT id FROM public.clients WHERE name='UBL'         LIMIT 1),NULL,'2026-06-22','Call',            'POC: Kamran Mirza. He requested 10% discount on package. Checking internally before reverting.', 'Pending','Revert with management decision on discount', '2026-06-24');

-- ── Ans ──
INSERT INTO public.follow_ups (client_id, deal_id, follow_up_date, type, notes, status, next_action, next_follow_up_date) VALUES
((SELECT id FROM public.clients WHERE name='Adcom'                       LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Ans' AND name LIKE '%Adcom%' LIMIT 1),   '2026-06-16','Call',            'POC: Lubna Pasha. Discuss next K&N campaign for Q2 FY26-27. New product rumoured in August.', 'Pending','Share Q2 digital calendar options', '2026-06-20'),
((SELECT id FROM public.clients WHERE name='Adcom'                       LIMIT 1),NULL,'2026-03-30','Call',            'POC: Lubna Pasha. K&N Q1 campaign wrapped up. Client satisfied. Discussed Q2 renewal.', 'Done',     'Send campaign performance report', '2026-04-10'),
((SELECT id FROM public.clients WHERE name='Media Networks'              LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Ans' AND name LIKE '%Media Networks%' LIMIT 1),'2026-06-18','Email',   'POC: Shahid Iqbal. Q4 digital package RO confirmed — share placement schedule and invoice.', 'Pending', 'Issue invoice for Q4 package', '2026-06-20'),
((SELECT id FROM public.clients WHERE name='Media Networks'              LIMIT 1),NULL,'2026-06-10','In-Person Meeting','POC: Shahid Iqbal. Lahore visit to Media Networks. Q4 renewal confirmed. They want to add HUM News Urdu this time.', 'Done','Add HUM News Urdu option to deal sheet', '2026-06-15'),
((SELECT id FROM public.clients WHERE name='EBM (English Biscuit Makers)' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Ans' AND name LIKE '%EBM%' LIMIT 1),   '2026-06-24','Presentation',  'POC: Zehra Hussain (EBM) + Sana Tariq (Starcom). Present Season 2 drama proposal with slot options.', 'Pending','Send post-presentation follow-up email', '2026-06-26'),
((SELECT id FROM public.clients WHERE name='EBM (English Biscuit Makers)' LIMIT 1),NULL,'2026-06-05','Call',           'POC: Zehra Hussain. EBM interested in Season 2 after positive Season 1 results. Budget Rs 2.2M.', 'Done',  'Prepare Season 2 proposal', '2026-06-15'),
((SELECT id FROM public.clients WHERE name='Media Networks'              LIMIT 1),NULL,'2026-05-25','WhatsApp',        'POC: Shahid Iqbal. Sent Q3 performance dashboard for Media Networks campaigns. Numbers looking good.', 'Done','Schedule renewal meeting', '2026-06-10'),
((SELECT id FROM public.clients WHERE name='Adcom'                       LIMIT 1),NULL,'2026-05-05','Email',           'POC: Lubna Pasha. Shared K&N campaign completion report — 2.3M impressions, 18% engagement rate.', 'Done','Discuss Q2 renewal at next call', '2026-06-16'),
((SELECT id FROM public.clients WHERE name='EBM (English Biscuit Makers)' LIMIT 1),NULL,'2026-05-28','Call',           'POC: Zehra Hussain. First contact for Season 2 — very warm. Budget confirmed at PKR 2-2.5M.', 'Done',  'Schedule presentation date', '2026-06-05'),
((SELECT id FROM public.clients WHERE name='Media Networks'              LIMIT 1),NULL,'2026-06-26','Call',            'POC: Shahid Iqbal. Confirm HUM News Urdu rates for Q4 add-on. He wants it included in existing deal.', 'Pending','Adjust deal sheet and re-send for approval', '2026-06-28');

-- ── Meesum ──
INSERT INTO public.follow_ups (client_id, deal_id, follow_up_date, type, notes, status, next_action, next_follow_up_date) VALUES
((SELECT id FROM public.clients WHERE name='Starcrest'       LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Meesum' AND name LIKE '%Starcrest%' LIMIT 1),  '2026-06-22','Email',           'POC: Amna Rehman. Q3 social bundle RO timeline. She expects RO by June 25 from her client.', 'Pending','Follow up again if no RO by June 25', '2026-06-25'),
((SELECT id FROM public.clients WHERE name='Starcrest'       LIMIT 1),NULL,'2026-06-10','Call',           'POC: Amna Rehman. Starcrest Q3 social deal locked — 3 brands, 30 posts, 3 months. Great win.', 'Done',   'Send deal confirmation and invoice draft', '2026-06-15'),
((SELECT id FROM public.clients WHERE name='Digital Creation' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Meesum' AND name LIKE '%Digital Creation%' LIMIT 1),'2026-06-20','Presentation','POC: Bilal Hassan. Formal pitch — HUM News website traffic report and banner placement proposal.', 'Pending','Follow up 2 days after presentation', '2026-06-22'),
((SELECT id FROM public.clients WHERE name='Digital Creation' LIMIT 1),NULL,'2026-06-05','Call',           'POC: Bilal Hassan (Digital Creation Lahore). Initial outreach — interested in HUM News website placement.', 'Done','Schedule pitch presentation', '2026-06-15'),
((SELECT id FROM public.clients WHERE name='Digital Marvels' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Meesum' AND name LIKE '%SMOG%' LIMIT 1),      '2026-01-25','Email',           'POC: Raheela Saeed. Campaign completion report sent. SMOG campaign delivered — 5 posts, 3 news articles.', 'Done','Explore next campaign for spring season', '2026-03-01'),
((SELECT id FROM public.clients WHERE name='Digital Marvels' LIMIT 1),NULL,'2026-06-18','Call',           'POC: Raheela Saeed. Post-SMOG follow-up — explore spring/summer govt campaign opportunities.', 'Pending','Pitch MOIB or Punjab Govt campaign options', '2026-06-22'),
((SELECT id FROM public.clients WHERE name='Starcrest'       LIMIT 1),NULL,'2026-05-28','In-Person Meeting','POC: Amna Rehman. Starcrest HQ visit. Presented Q3 social package options — she loved the HUM TV Insta stats.', 'Done','Send formal proposal', '2026-06-05'),
((SELECT id FROM public.clients WHERE name='Digital Creation' LIMIT 1),NULL,'2026-05-20','WhatsApp',      'POC: Bilal Hassan. Sent HUM News readership stats (2.1M monthly unique visitors) — he was impressed.', 'Done','Schedule call', '2026-06-05'),
((SELECT id FROM public.clients WHERE name='Starcrest'       LIMIT 1),NULL,'2026-06-26','Call',           'POC: Amna Rehman. Check if RO is with finance for approval. Confirm billing entity name.', 'Pending',   'Book Q3 posting slots once RO confirmed', '2026-06-28'),
((SELECT id FROM public.clients WHERE name='Digital Marvels' LIMIT 1),NULL,'2026-07-05','Email',          'POC: Raheela Saeed. Pitch summer govt campaign — MOIB or BISP. Timing good for Q1 FY26-27.', 'Pending', 'Prepare govt campaign case study', '2026-07-08');

-- ─────────────────────────────────────────────────────────────
-- 6. MEETING LOGS — 5 per team member (~35 total)
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.meeting_logs (client_id, deal_id, meeting_date, type, outcome, deal_status_after, notes, next_steps) VALUES

-- Aamish Mirza
((SELECT id FROM public.clients WHERE name='Haier Pakistan' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%Haier%' LIMIT 1),'2026-06-08','Online',       'Positive — Haier agreed on 10 posts for HUM Awards. Rates finalised at PKR 1.2M.', 'In Negotiation','POC: Wang Li. Teams call. Contract being finalised.',         'Get contract signed by June 15'),
((SELECT id FROM public.clients WHERE name='K&N''s Foods'   LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%K&N%' LIMIT 1),  '2026-06-05','In-Person',    'K&N team enthusiastic. Banner slots confirmed for Jul-Sep. Deal locked.', 'Locked',          'POC: Tariq Hassan. Met at K&N Clifton HQ. 3 of his team attended.',   'Issue invoice by June 20 once RO received'),
((SELECT id FROM public.clients WHERE name='BYD Pakistan'   LIMIT 1),NULL,                                                                                           '2026-06-12','Online',       'Exploratory — BYD marketing head interested but needs internal budget approval.', 'Prospecting',  'POC: Chen Wei + 2 colleagues. Presented HUM TV reach for auto segment.',  'Present case study on June 25'),
((SELECT id FROM public.clients WHERE name='Bank Alfalah'   LIMIT 1),NULL,                                                                                           '2026-05-30','Phone Call',   'Alfalah confirmed interest in Instagram posts for summer campaign.', 'Pitch Sent',          'POC: Saima Khan. Brief call. She asked for formal proposal.',          'Send proposal by June 10'),
((SELECT id FROM public.clients WHERE name='Haier Pakistan' LIMIT 1),NULL,                                                                                           '2026-05-12','In-Person',    'Haier reviewed Q1 campaign performance. Very happy. Wants to continue Q3.', 'In Negotiation', 'POC: Wang Li. Haier Lahore office visit.',                          'Prepare Q3 renewal proposal'),

-- Sarfaraz
((SELECT id FROM public.clients WHERE name='Nestlé Pakistan' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%Nestlé%' LIMIT 1),'2026-06-08','In-Person',   'Nestlé team approved creative direction for Spelling Whizz 2026. Budget confirmed PKR 20M.', 'Under Process','POC: Zulfiqar Ali + Saad Malik. Met at Nestlé Lahore HQ. 4 people.','Chase HO approval — expected by June 25'),
((SELECT id FROM public.clients WHERE name='Pak Media Com'   LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%Ramzan%' LIMIT 1),'2026-06-03','Online',      'Pak Media Com finalised Ramzan drama slot. RO being prepared.', 'Locked',                    'POC: Saad Malik. Video call — deal closed in this meeting.',           'Receive RO and issue invoice'),
((SELECT id FROM public.clients WHERE name='OGDCL'           LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%OGDCL%' LIMIT 1),'2026-05-25','In-Person',   'OGDCL team very positive on 8-week digital awareness campaign. RO issued same day.', 'RO Received', 'POC: Dr. Nadeem Babar. OGDCL Islamabad HQ.',                         'Start campaign July 1 as planned'),
((SELECT id FROM public.clients WHERE name='Nestlé Pakistan' LIMIT 1),NULL,                                                                                         '2026-05-10','Presentation','Presented Spelling Whizz 2025 ROI report. Nestlé team impressed — ROAS 3.2x vs. benchmark.', 'Under Process','POC: Zulfiqar Ali. Formal boardroom presentation.',               'Submit 2026 proposal within 7 days'),
((SELECT id FROM public.clients WHERE name='Pak Media Com'   LIMIT 1),NULL,                                                                                         '2026-05-20','Online',      'Explored other brands in Pak Media Com portfolio for drama slots — 3 names shortlisted.', 'Prospecting','POC: Saad Malik. Pipeline discussion call.',                        'Prepare individual proposals for 3 brands'),

-- Talal
((SELECT id FROM public.clients WHERE name='HBL'                  LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Talal' AND name LIKE '%Clock%' LIMIT 1),'2026-03-20','Online',    'HBL confirmed satisfaction with clock widget. Discussed Q3 drama add-on.', 'Billed',           'POC: Aisha Baig. Post-campaign review call.',                         'Propose Q3 drama integration package'),
((SELECT id FROM public.clients WHERE name='BrainChild / Starcom' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Talal' AND name LIKE '%Starcom%' LIMIT 1),'2026-06-15','In-Person','Rate negotiation for Q3 drama package (Dawlance + HBL). Starcom asked for 15% discount.', 'In Negotiation','POC: Sana Tariq. BrainChild/Starcom Karachi office.',             'Check discount feasibility with management'),
((SELECT id FROM public.clients WHERE name='SNGPL'                LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Talal' AND name LIKE '%SNGPL%' LIMIT 1),'2026-05-28','Phone Call', 'SNGPL via Hakuna Matata — campaign confirmed for 4 months (May-Aug). Good recurring revenue.', 'Locked',      'POC: Usama Khan (Hakuna Matata acting as middleman).',               'Book all placement slots for 4-month block'),
((SELECT id FROM public.clients WHERE name='HBL'                  LIMIT 1),NULL,'2026-05-20','In-Person',    'Post-campaign review with HBL. Clock widget drove 180K clicks. Exploring Q3 drama integration.', 'Locked','POC: Aisha Baig. HBL Tower Karachi.',                                 'Build drama integration proposal for Q3'),
((SELECT id FROM public.clients WHERE name='BrainChild / Starcom' LIMIT 1),NULL,'2026-05-28','Online',       'Q3 pipeline review with Starcom. They have 4 brands considering HUM TV — Dawlance is biggest one.', 'In Negotiation','POC: Sana Tariq. Monthly agency pipeline review.',               'Send customised proposals for each brand'),

-- Asif
((SELECT id FROM public.clients WHERE name='Jazz (Mobilink)' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%Jazz%' LIMIT 1),    '2026-06-05','In-Person',   'Annual review with Jazz leadership. FY26-27 deal extended with 10% budget increase to PKR 16.5M.', 'Locked',  'POC: Omer Sheikh + 2 others. Jazz HQ Islamabad.',                    'Finalise drama placement schedule for FY26-27'),
((SELECT id FROM public.clients WHERE name='IG Square'       LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%IG Square%' LIMIT 1),'2026-06-01','In-Person',   'IG Square RO received. BCW + HUM Awards package confirmed PKR 12M. Biggest event deal of year.', 'RO Received','POC: Imran Ghazi. IG Square Karachi office.',                       'Brief events team and issue invoice'),
((SELECT id FROM public.clients WHERE name='GroupM'          LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%GroupM%' LIMIT 1),   '2026-05-22','Phone Call',  'Cold reconnect with GroupM after 6 months. Zara open to meeting. Scheduled July 5 pitch.', 'Prospecting',  'POC: Zara Hussain. Reconnect call after long gap.',                  'Prepare comprehensive pitch deck for July 5'),
((SELECT id FROM public.clients WHERE name='Mesh Media'      LIMIT 1),NULL,'2026-06-14','Online',       'Haier HUM Awards campaign delivered. Client very happy. 1.2M post impressions.', 'Billed',         'POC: Raza Shah. Post-campaign success call.',                         'Explore Q3 Haier renewal and BCW 2026'),
((SELECT id FROM public.clients WHERE name='Jazz (Mobilink)' LIMIT 1),NULL,'2026-05-10','Online',       'Mid-year performance review — Jazz very satisfied with drama placements. Confirmed FY26-27 continuation.', 'Locked','POC: Omer Sheikh. Biannual performance review.',                  'Schedule annual contract renewal meeting'),

-- Erum
((SELECT id FROM public.clients WHERE name='UBL'         LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Erum' AND name LIKE '%UBL%' LIMIT 1),      '2026-06-08','Presentation','Presented HUM News website analytics + Glam Magazine demographics to UBL team. Good interest.', 'Pitch Sent','POC: Kamran Mirza + marketing team. UBL Tower Karachi.',             'Follow up on pricing approval'),
((SELECT id FROM public.clients WHERE name='Wings Media' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Erum' AND name LIKE '%Wings%' LIMIT 1),    '2026-06-10','In-Person',   'Wings Media confirmed Ramzan 2027 bundle. Multiple brands under umbrella confirmed.', 'Under Process','POC: Ahsan Rao. Wings Media office Karachi.',                       'Get final brand list for campaign brief'),
((SELECT id FROM public.clients WHERE name='Dawlance'    LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Erum' AND name LIKE '%Dawlance%' LIMIT 1), '2026-06-12','Online',      'Dawlance product launch confirmed in drama + Masala TV morning show. Deal locked Rs 1.8M.', 'Locked',    'POC: Faisal Niaz + Sana Tariq (Starcom). Three-way call.',            'Issue invoice and brief content team'),
((SELECT id FROM public.clients WHERE name='UBL'         LIMIT 1),NULL,'2026-05-25','Phone Call',   'Initial outreach to UBL digital team. They are planning a campaign for Q1 FY26-27.', 'Pitch Sent',     'POC: Kamran Mirza. Cold outreach call.',                              'Schedule formal presentation'),
((SELECT id FROM public.clients WHERE name='Dawlance'    LIMIT 1),NULL,'2026-05-20','In-Person',    'Visited Dawlance showroom Karachi with Starcom to present integration options. Very positive.', 'Locked',  'POC: Faisal Niaz. Showroom visit with agency team.',                  'Formalise deal sheet with Starcom'),

-- Ans
((SELECT id FROM public.clients WHERE name='Adcom'                       LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Ans' AND name LIKE '%Adcom%' LIMIT 1),   '2026-02-15','In-Person','K&N campaign brief finalised with Adcom. Launched on time. All placements confirmed.', 'Completed',  'POC: Lubna Pasha. Adcom Karachi office.',                             'Send campaign report after completion'),
((SELECT id FROM public.clients WHERE name='Media Networks'              LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Ans' AND name LIKE '%Media Networks%' LIMIT 1),'2026-06-10','In-Person','Lahore visit — Media Networks Q4 renewal signed. Adding HUM News Urdu to package.', 'RO Received','POC: Shahid Iqbal. Media Networks Lahore HQ.',                       'Update deal sheet and issue invoice'),
((SELECT id FROM public.clients WHERE name='EBM (English Biscuit Makers)' LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Ans' AND name LIKE '%EBM%' LIMIT 1),   '2026-06-24','Presentation','Season 2 drama sponsorship pitch to EBM + Starcom. Strong interest — decision expected in 2 weeks.', 'In Negotiation','POC: Zehra Hussain + Sana Tariq. EBM head office.',             'Follow up by July 8 for decision'),
((SELECT id FROM public.clients WHERE name='Adcom'                       LIMIT 1),NULL,'2026-03-30','Online',    'K&N Q1 wrap-up call. Campaign exceeded targets — 2.3M impressions. Client wants Q2 renewal.', 'Completed','POC: Lubna Pasha. Post-campaign review.',                            'Prepare Q2 renewal proposal'),
((SELECT id FROM public.clients WHERE name='Media Networks'              LIMIT 1),NULL,'2026-05-25','Online',    'Q3 performance review with Media Networks. All 3 campaigns hit targets. Strong case for renewal.', 'RO Received','POC: Shahid Iqbal. Quarterly review call.',                     'Schedule in-person Lahore meeting'),

-- Meesum
((SELECT id FROM public.clients WHERE name='Starcrest'        LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Meesum' AND name LIKE '%Starcrest%' LIMIT 1), '2026-06-10','In-Person','Starcrest Q3 social deal closed. 30 posts, 3 brands, 3 months. PKR 1.8M locked.', 'Locked',          'POC: Amna Rehman. Starcrest HQ Karachi.',                             'Issue invoice and get posting schedule'),
((SELECT id FROM public.clients WHERE name='Digital Creation'  LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Meesum' AND name LIKE '%Digital Creation%' LIMIT 1),'2026-06-20','Presentation','Presented HUM News digital package to Digital Creation Lahore team. Very positive reception.', 'Pitch Sent','POC: Bilal Hassan. Online pitch presentation.',                   'Follow up in 2 days for decision'),
((SELECT id FROM public.clients WHERE name='Digital Marvels'  LIMIT 1),(SELECT id FROM public.deals WHERE assigned_to='Meesum' AND name LIKE '%SMOG%' LIMIT 1),      '2026-01-20','Online',    'SMOG campaign delivery review. All 5 posts published. 3 news articles live. Client happy.', 'Completed',   'POC: Raheela Saeed. Campaign wrap-up call.',                          'Explore spring campaign opportunity'),
((SELECT id FROM public.clients WHERE name='Starcrest'        LIMIT 1),NULL,'2026-05-28','In-Person','Starcrest initial pitch — presented HUM TV and HUM News social stats. Very impressed with numbers.', 'Locked','POC: Amna Rehman. Starcrest Karachi.',                               'Send formal proposal'),
((SELECT id FROM public.clients WHERE name='Digital Marvels'  LIMIT 1),NULL,'2026-06-18','Phone Call','Reconnect call with Digital Marvels — pitching summer govt campaign. Interested in MOIB options.', 'Prospecting','POC: Raheela Saeed. Exploratory call.',                            'Prepare MOIB/BISP campaign proposal');

-- ─────────────────────────────────────────────────────────────
-- 7. INVOICES
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.invoices (invoice_number, client_id, deal_id, invoice_date, amount_net, due_date, payment_date, amount_received, status) VALUES
('DIG-26-001', (SELECT id FROM public.clients WHERE name='Jazz (Mobilink)' LIMIT 1),      (SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%Jazz%' LIMIT 1),        '2026-07-01', 16500000, '2026-07-31', NULL,         0,        'Unpaid'),
('DIG-26-002', (SELECT id FROM public.clients WHERE name='IG Square' LIMIT 1),            (SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%IG Square%' LIMIT 1),   '2026-06-10', 12000000, '2026-07-10', NULL,         4000000,  'Partial'),
('DIG-26-003', (SELECT id FROM public.clients WHERE name='Nestlé Pakistan' LIMIT 1),      (SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%Nestlé%' LIMIT 1),  '2026-06-15',  5000000, '2026-07-15', NULL,         0,        'Unpaid'),
('DIG-26-004', (SELECT id FROM public.clients WHERE name='OGDCL' LIMIT 1),                (SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%OGDCL%' LIMIT 1),   '2026-06-01',  4000000, '2026-06-30', '2026-06-20', 4000000,  'Paid'),
('DIG-26-005', (SELECT id FROM public.clients WHERE name='HBL' LIMIT 1),                  (SELECT id FROM public.deals WHERE assigned_to='Talal' AND name LIKE '%Clock%' LIMIT 1),      '2026-03-15',  3500000, '2026-04-15', '2026-04-28', 3500000,  'Paid'),
('DIG-26-006', (SELECT id FROM public.clients WHERE name='Pak Media Com' LIMIT 1),        (SELECT id FROM public.deals WHERE assigned_to='Sarfaraz' AND name LIKE '%Ramzan%' LIMIT 1),  '2026-06-08',  3500000, '2026-07-08', NULL,         0,        'Unpaid'),
('DIG-26-007', (SELECT id FROM public.clients WHERE name='Dawlance' LIMIT 1),             (SELECT id FROM public.deals WHERE assigned_to='Erum' AND name LIKE '%Dawlance%' LIMIT 1),    '2026-06-18',  1800000, '2026-07-18', NULL,         900000,   'Partial'),
('DIG-26-008', (SELECT id FROM public.clients WHERE name='Mesh Media' LIMIT 1),           (SELECT id FROM public.deals WHERE assigned_to='Asif' AND name LIKE '%Mesh Media%' LIMIT 1),  '2026-06-10',  1500000, '2026-07-10', '2026-06-25', 1500000,  'Paid'),
('DIG-26-009', (SELECT id FROM public.clients WHERE name='Media Networks' LIMIT 1),       (SELECT id FROM public.deals WHERE assigned_to='Ans' AND name LIKE '%Media Networks%' LIMIT 1),'2026-04-05',  1500000, '2026-05-05', '2026-05-20', 1500000,  'Paid'),
('DIG-25-041', (SELECT id FROM public.clients WHERE name='Digital Marvels' LIMIT 1),      (SELECT id FROM public.deals WHERE assigned_to='Meesum' AND name LIKE '%SMOG%' LIMIT 1),      '2025-12-05',   350000, '2026-01-05', '2026-01-15',  350000,  'Paid'),
('DIG-26-010', (SELECT id FROM public.clients WHERE name='Adcom' LIMIT 1),                (SELECT id FROM public.deals WHERE assigned_to='Ans' AND name LIKE '%Adcom%' LIMIT 1),        '2026-01-20',   450000, '2026-02-20', '2026-03-05',  450000,  'Paid'),
('DIG-26-011', (SELECT id FROM public.clients WHERE name='K&N''s Foods' LIMIT 1),         (SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%K&N%' LIMIT 1), '2026-06-20',   450000, '2026-07-20', NULL,              0,  'Unpaid');

-- ─────────────────────────────────────────────────────────────
-- 8. TRAVEL RECORDS
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.travel_records (start_date, end_date, destination, purpose, client_id, mode, accommodation, transport, meals, budget, notes) VALUES
('2026-06-08','2026-06-08','Lahore','Client meetings — Nestlé HQ and Media Networks',(SELECT id FROM public.clients WHERE name='Nestlé Pakistan' LIMIT 1),'Flight',  0,    18000, 3000, 25000,'Sarfaraz. Day trip. Nestlé HQ AM, Media Networks PM. Both meetings productive.'),
('2026-06-10','2026-06-10','Lahore','Starcrest and Digital Creation client visits',  (SELECT id FROM public.clients WHERE name='Starcrest' LIMIT 1),      'Flight',  0,    18000, 2500, 25000,'Meesum. Starcrest pitch AM, Digital Creation lunch meeting. Q3 deal closed with Starcrest.'),
('2026-05-25','2026-05-26','Islamabad','OGDCL meeting and Jazz HQ visit',            (SELECT id FROM public.clients WHERE name='OGDCL' LIMIT 1),           'Flight',  12000, 18000, 5000, 40000,'Sarfaraz + Asif. Overnight trip. OGDCL RO collected. Jazz annual renewal discussion.'),
('2026-06-01','2026-06-01','Islamabad','Jazz annual review meeting',                  (SELECT id FROM public.clients WHERE name='Jazz (Mobilink)' LIMIT 1), 'Flight',  0,    18000, 3000, 25000,'Asif. Day trip. Jazz HQ. Annual FY26-27 contract signed. Deal extended Rs 16.5M.'),
('2026-05-20','2026-05-20','Karachi — Clifton','K&N HQ visit and BYD Pakistan office',(SELECT id FROM public.clients WHERE name='K&N''s Foods' LIMIT 1),  'Car',     0,     2500, 1500, 5000, 'Aamish Mirza. K&N meeting 10AM, BYD exploratory visit 2PM. K&N deal locked.'),
('2026-06-10','2026-06-11','Lahore','Media Networks quarterly review + Pak Media Com',(SELECT id FROM public.clients WHERE name='Media Networks' LIMIT 1),  'Train',   8000,  3500, 4000, 20000,'Ans. Overnight. Media Networks Q4 renewal signed. Pak Media Com pipeline discussion.'),
('2026-05-28','2026-05-28','Karachi — DHA','Adcom and Wings Media visits',            (SELECT id FROM public.clients WHERE name='Adcom' LIMIT 1),           'Car',     0,     2000, 2000, 5000, 'Ans. Adcom meeting 11AM, Wings Media 3PM. Both positive outcomes.'),
('2026-06-12','2026-06-12','Karachi — Gulshan','Dawlance showroom and UBL Tower',     (SELECT id FROM public.clients WHERE name='Dawlance' LIMIT 1),         'Car',     0,     1500, 2000, 5000, 'Erum. Dawlance product launch brief done. UBL meeting for digital campaign.'),
('2026-06-05','2026-06-05','Islamabad','IG Square event planning meeting',            (SELECT id FROM public.clients WHERE name='IG Square' LIMIT 1),        'Flight',  0,    18000, 3000, 25000,'Asif. BCW 2026 activation plan reviewed with IG Square. RO collected same day.'),
('2026-05-15','2026-05-15','Karachi — PECHS','HBL Tower post-campaign review',        (SELECT id FROM public.clients WHERE name='HBL' LIMIT 1),              'Car',     0,      800, 1200, 4000, 'Talal. Clock widget post-campaign review. HBL very satisfied — Q3 renewal on the table.');

-- ─────────────────────────────────────────────────────────────
-- 9. PRODUCTION EXPENSES
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.production_expenses (show_id, expense_type, vendor, date, amount, po_number, invoice_received, budget_code, notes) VALUES
((SELECT id FROM public.shows WHERE name='Hum Kalam' LIMIT 1),          'Crew',            'Creative Shoot Studios',   '2026-05-20', 850000,  'PO-HK-001', true,  'PROD-2026-001', 'Full crew for Hum Kalam episode 75-85 block. Director + 40-person crew.'),
((SELECT id FROM public.shows WHERE name='Hum Kalam' LIMIT 1),          'Post-Production', 'Edgewater Post',           '2026-06-01', 320000,  'PO-HK-002', true,  'PROD-2026-002', 'Color grading + sound mix for episodes 80-85.'),
((SELECT id FROM public.shows WHERE name='Good Morning Pakistan' LIMIT 1),'Crew',           'Spark Productions',        '2026-06-05', 240000,  'PO-GMP-001',true,  'PROD-2026-003', 'Monthly crew cost for Good Morning Pakistan — 4-week production.'),
((SELECT id FROM public.shows WHERE name='Good Morning Pakistan' LIMIT 1),'Equipment',      'Broadcast Rentals Pvt Ltd','2026-06-05', 180000,  'PO-GMP-002',true,  'PROD-2026-004', 'Studio equipment rental — cameras, lighting rig, teleprompter, June cycle.'),
((SELECT id FROM public.shows WHERE name='Raqs-e-Bismil' LIMIT 1),       'Post-Production', 'Studio X Post',            '2026-03-15', 650000,  'PO-RB-001', true,  'PROD-2026-005', 'Final post-production for last 8 episodes of Raqs-e-Bismil. Color + VFX.'),
((SELECT id FROM public.shows WHERE name='Dil Awaiz' LIMIT 1),           'Location',        'Gulshan Sets Pvt Ltd',     '2026-06-10', 420000,  'PO-DA-001', false, 'PROD-2026-006', 'Set construction for Dil Awaiz — 3 main sets. Shoot starts August 1.'),
((SELECT id FROM public.shows WHERE name='Dil Awaiz' LIMIT 1),           'Talent',          'Talent Connect Pakistan',  '2026-06-12', 1200000, 'PO-DA-002', false, 'PROD-2026-007', 'Lead cast contracting for Dil Awaiz — 2 leads, 4 supporting. 24-episode drama.'),
((SELECT id FROM public.shows WHERE name='Masala Mornings' LIMIT 1),     'Misc',            'Prop House Karachi',       '2026-06-01', 85000,   'PO-MM-001', true,  'PROD-2026-008', 'Monthly prop and set dressing for Masala Mornings cooking segments.');

-- ─────────────────────────────────────────────────────────────
-- 10. DELIVERABLES
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.deliverables (deal_id, client_id, type, platform, channel, qty_committed, qty_delivered, due_date, status, notes) VALUES
((SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%Haier%' LIMIT 1),   (SELECT id FROM public.clients WHERE name='Haier Pakistan' LIMIT 1),                'Social Media Posts',       'Instagram',         'HUM TV',      10, 0,  '2026-06-30', 'Pending',     'HUM Awards coverage posts. Mix of Reels and static. Creative assets awaited from client.'),
((SELECT id FROM public.deals WHERE assigned_to='Aamish Mirza' AND name LIKE '%K&N%'   LIMIT 1),   (SELECT id FROM public.clients WHERE name='K&N''s Foods' LIMIT 1),                  'Website Banner Impressions','HUM Network Website','HUM Network',  1, 0,  '2026-07-31', 'Pending',     'Homepage banner 728x90 + sidebar 300x250. 500K impressions committed for July.'),
((SELECT id FROM public.deals WHERE assigned_to='Sarfaraz'    AND name LIKE '%OGDCL%'  LIMIT 1),   (SELECT id FROM public.clients WHERE name='OGDCL' LIMIT 1),                          'Social Media Posts',       'Instagram + Facebook','HUM News',   12, 0,  '2026-08-31', 'Pending',     'Corporate awareness posts — 3 posts/week for 4 weeks per platform. Launching July 1.'),
((SELECT id FROM public.deals WHERE assigned_to='Talal'       AND name LIKE '%Clock%'  LIMIT 1),   (SELECT id FROM public.clients WHERE name='HBL' LIMIT 1),                            'Website Banner Impressions','HUM News Urdu',     'HUM News',     1, 1,  '2026-03-31', 'Delivered',   'Clock widget placement — 2M impressions delivered Mar 2026. Final report sent to client.'),
((SELECT id FROM public.deals WHERE assigned_to='Asif'        AND name LIKE '%IG Square%' LIMIT 1),(SELECT id FROM public.clients WHERE name='IG Square' LIMIT 1),                     'Branded Post',             'Instagram',         'HUM TV',       8, 0,  '2026-09-30', 'Pending',     'BCW 2026 branded posts — 4 Instagram Reels + 4 static. Schedule to be shared with agency.'),
((SELECT id FROM public.deals WHERE assigned_to='Asif'        AND name LIKE '%IG Square%' LIMIT 1),(SELECT id FROM public.clients WHERE name='IG Square' LIMIT 1),                     'Event Sponsorship',        'BCW + HUM Awards',  'HUM TV',       2, 0,  '2026-12-31', 'Pending',     'Stage branding and media wall placement at BCW and HUM Awards 2026.'),
((SELECT id FROM public.deals WHERE assigned_to='Asif'        AND name LIKE '%Mesh Media%' LIMIT 1),(SELECT id FROM public.clients WHERE name='Haier Pakistan' LIMIT 1),               'Branded Post',             'Instagram',         'HUM TV',       5, 5,  '2026-06-30', 'Delivered',   'HUM Awards Haier integration posts — all 5 published, 1.2M impressions. Campaign closed.'),
((SELECT id FROM public.deals WHERE assigned_to='Erum'        AND name LIKE '%Dawlance%' LIMIT 1), (SELECT id FROM public.clients WHERE name='Dawlance' LIMIT 1),                      'Product Integration',      'Masala TV Mornings','Masala TV',   4,  0,  '2026-10-31', 'Pending',     'Dawlance product placement in 4 Masala Mornings cooking segments. Integration brief TBD.'),
((SELECT id FROM public.deals WHERE assigned_to='Erum'        AND name LIKE '%Wings%'   LIMIT 1),  (SELECT id FROM public.clients WHERE name='Wings Media' LIMIT 1),                   'Social Media Posts',       'Instagram',         'HUM TV',      20,  0,  '2027-04-30', 'Pending',     'Ramzan 2027 social bundle — 20 branded posts across Ramzan period. Creative to be supplied by Wings.'),
((SELECT id FROM public.deals WHERE assigned_to='Ans'         AND name LIKE '%Adcom%'   LIMIT 1),  (SELECT id FROM public.clients WHERE name='K&N''s Foods' LIMIT 1),                  'Website Banner Impressions','HUM Network',       'HUM Network',  1,  1,  '2026-03-31', 'Delivered',   'K&N product launch banners — 750K impressions, 2.3M total reach. Campaign completed March 2026.'),
((SELECT id FROM public.deals WHERE assigned_to='Ans'         AND name LIKE '%Media Networks%' LIMIT 1),(SELECT id FROM public.clients WHERE name='Media Networks' LIMIT 1),          'Website Banner Impressions','HUM News Website',  'HUM News',     1,  0,  '2026-06-30', 'In Progress', 'Q4 digital banner package — HUM News Urdu + HUM News English. 400K impressions committed.'),
((SELECT id FROM public.deals WHERE assigned_to='Meesum'      AND name LIKE '%Starcrest%' LIMIT 1),(SELECT id FROM public.clients WHERE name='Starcrest' LIMIT 1),                    'Social Media Posts',       'Instagram',         'HUM TV',      15,  0,  '2026-09-30', 'Pending',     'Q3 social bundle for Starcrest brands — 5 posts/month for 3 months. Creative to come from agency.'),
((SELECT id FROM public.deals WHERE assigned_to='Meesum'      AND name LIKE '%SMOG%'    LIMIT 1),  (SELECT id FROM public.clients WHERE name='Digital Marvels' LIMIT 1),               'Social Media Posts',       'Instagram + Facebook','HUM News',   5,  5,  '2025-12-31', 'Delivered',   'SMOG awareness campaign — 5 posts delivered, 3 news articles published. All done.'),
((SELECT id FROM public.deals WHERE assigned_to='Sarfaraz'    AND name LIKE '%Ramzan%'  LIMIT 1),  (SELECT id FROM public.clients WHERE name='Pak Media Com' LIMIT 1),                 'Drama Sponsorship',        'HUM TV',            'HUM TV',       1,  0,  '2027-03-31', 'Pending',     'Ramzan 2027 presenting slot — 1 prime drama sponsorship. Drama title to be confirmed by August.'),
((SELECT id FROM public.deals WHERE assigned_to='Talal'       AND name LIKE '%SNGPL%'  LIMIT 1),   (SELECT id FROM public.clients WHERE name='SNGPL' LIMIT 1),                         'Website Banner Impressions','HUM News Urdu',     'HUM News',     4,  1,  '2026-08-31', 'In Progress', 'Monthly banner block May–Aug 2026. May delivered (100K impr). June-Aug remaining.');

-- ─────────────────────────────────────────────────────────────
-- Done! Verify with:
-- SELECT 'clients' AS tbl, COUNT(*) FROM public.clients
-- UNION ALL SELECT 'deals', COUNT(*) FROM public.deals
-- UNION ALL SELECT 'follow_ups', COUNT(*) FROM public.follow_ups
-- UNION ALL SELECT 'meeting_logs', COUNT(*) FROM public.meeting_logs
-- UNION ALL SELECT 'invoices', COUNT(*) FROM public.invoices
-- UNION ALL SELECT 'travel_records', COUNT(*) FROM public.travel_records
-- UNION ALL SELECT 'production_expenses', COUNT(*) FROM public.production_expenses
-- UNION ALL SELECT 'deliverables', COUNT(*) FROM public.deliverables;
-- ─────────────────────────────────────────────────────────────
